version: '3.8'

services:
  # Contenidor per al servidor web amb PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Assegura't que tens el Dockerfile aquí
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  # Contenidor per a la base de dades MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Canvia això per una contrasenya segura
      MYSQL_DATABASE: projecttest   # Canvia-ho pel nom de la base de dades que necessites
      MYSQL_USER: admin                    # Nom d'usuari de MySQL
      MYSQL_PASSWORD: admin       # Contrasenya de l'usuari de MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

# Xarxa compartida entre els serveis
networks:
  app-network:

# Volum per guardar les dades de MySQL
volumes:
  db_data:
